achievesolapp/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'achievesolapp'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/', views.about, name='about'),
    url(r'^services/', views.services, name='services'),
    url(r'^programs/', views.programs, name='programs'), 
    url(r'^videos/', views.videos, name='videos'),   
    url(r'^events/', views.product_list, name='product_list'),
    url(r'^media/', views.media_list, name='media_list'),
    url(r'^blog/', views.blog_list, name='blog_list'),
    url(r'^pastevents/', views.events404, name='events404'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^appointement/', views.appointement, name='appointement'),
    url(r'^eventbooking/', views.eventbooking, name='eventbooking'),
    url(r'^(?P<mediacategory_slug>[-\w]+)/$', views.media_list, name='media_list_by_category'), 
    url(r'^(?P<blogcategory_slug>[-\w]+)/$', views.blog_list, name='blog_list_by_category'), 
    url(r'^(?P<id>\d+)/(?P<blogcategory_slug>[-\w]+)/$', views.blog_detail, name='blog_detail'),
   
   
    

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

achievesoutions/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url ,include
from django.contrib.auth import views






urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url('admin/', admin.site.urls),
    url('', include('achievesolapp.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

achievesolapp/models.py
from django.db import models
from django.urls import reverse
from pyuploadcare.dj.models import ImageField
from imagekit.models import ImageSpecField 
from imagekit.processors import ResizeToFill 


class EventCategory(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'eventcategory'
        verbose_name_plural = 'eventcategories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('achievesolapp:product_list_by_Eventcategory', args=[self.slug])

class BlogCategory(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'blogcategory'
        verbose_name_plural = 'blogcategories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('achievesolapp:blog_list_by_category', args=[self.slug])


class MediaCategory(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'mediacategory'
        verbose_name_plural = 'mediacategories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('achievesolapp:media_list_by_category', args=[self.slug])



class Blog(models.Model):
    blogcategory = models.ForeignKey( BlogCategory, related_name='blogs', on_delete=models.CASCADE)
    blog_name = models.CharField(max_length=100, db_index=True)
    brief_description = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    date = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)
    blog_story = models.TextField(blank=True)
    image = ImageField(blank=True, null=True)
   
     
    class Meta:
        ordering = ('-created_at', ) 
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.blog_name

    def get_absolute_url(self):
        return reverse('achievesolapp:blog_detail', args=[self.id, self.slug])


class Event(models.Model):
    eventcategory = models.ForeignKey(EventCategory, related_name='events', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    brief_description = models.CharField(max_length=100, db_index=True)
    date = models.DateField(null=True, blank=True)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=100, db_index=True)
    brief_story = models.TextField(blank=True)
    location = models.CharField(null=True, max_length=100, db_index=True)
    venue = models.CharField(null=True, max_length=100, db_index=True)
    start_time = models.DateTimeField(null=True, blank=True)
    End_time = models.DateTimeField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = ImageField(blank=True, null=True,)
   
     
    class Meta:
        ordering = ('date', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('achievesolapp:product_list', args=[self.id, self.slug])


class Media(models.Model):
    mediacategory = models.ForeignKey(MediaCategory, related_name='medias', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ImageField(blank=True, null=True)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)
    

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('achievesolapp:media_list', args=[self.id, self.slug])

achievesolapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Event, Media, Blog, BlogCategory, MediaCategory, EventCategory



def product_list(request, eventcategory_slug=None):
    eventcategory = None
    eventcategories = EventCategory.objects.all()
    events = Event.objects.filter(available=True)
    if eventcategory_slug:
        eventcategory = get_object_or_404(EventCategory, slug=eventcategory_slug)
        events = Event.objects.filter(eventcategory=eventcategory)

    context = {
        'eventcategory': eventcategory,
        'eventcategories': eventcategories,
        'events': events
    }
    return render(request, 'achievesolapp/app/eventlist.html', context)

def blog_list(request, blogcategory_slug=None):
    blogcategory = None
    blogcategories = BlogCategory.objects.all()
    blogs = Blog.objects.filter(available=True)
    if blogcategory_slug:
        blogcategory = get_object_or_404(BlogCategory, slug=blogcategory_slug)
        blogs = Blog.objects.filter(blogcategory=blogcategory)

    context = {
        'blogcategory': blogcategory,
        'blogcategories': blogcategories,
        'blogs': blogs
    }
    return render(request, 'achievesolapp/app/bloglist.html', context)


def media_list(request, mediacategory_slug=None):
    mediacategory = None
    mediacategories = MediaCategory.objects.all()
    medias = Media.objects.filter(available=True)
    if mediacategory_slug:
        mediacategory = get_object_or_404(MediaCategory, slug=mediacategory_slug)
        medias = Media.objects.filter(mediacategory=mediacategory)

    context = {
        'mediacategory': mediacategory,
        'mediacategories': mediacategories,
        'medias': medias
    }
    return render(request, 'achievesolapp/app/medialist.html', context)







def blog_detail(request, id, blogcategory_slug):
    blog = get_object_or_404(Blog, id=id, slug=blogcategory_slug, available=True )
    context = {
        'blog': blog
        
    }
    return render(request, 'achievesolapp/app/blogdetail.html', context)


def home(request):
  return render(request, 'achievesolapp/app/index.html')

def about(request):
  return render(request, 'achievesolapp/app/about.html')

def programs(request):
  return render(request, 'achievesolapp/app/programs.html')

def services(request):
  return render(request, 'achievesolapp/app/services.html')

def videos(request):
  return render(request, 'achievesolapp/app/videos.html')

def contact(request):
  return render(request, 'achievesolapp/app/contact.html')

def events404(request):
  return render(request, 'achievesolapp/app/events404.html')

def appointement(request):
  return render(request, 'achievesolapp/app/bookingappointement.html')

def eventbooking(request):
  return render(request, 'achievesolapp/app/bookingevent.html')

achievesolapp/templates/achievesolapp/app/404-page.html
<!DOCTYPE html>
<html class="wow-animation" lang="en">
  <head>
    <!-- Site Title-->
    <title>404 Page</title>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <script src="/cdn-cgi/apps/head/3ts2ksMwXvKRuG480KNifJ2_JNM.js"></script><link rel="icon" href="images/favicon.ico" type="image/x-icon">
    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Montserrat:400,700%7CMerriweather:300,400,400i,700,700i%7CLato:400,400i,700,900">
    <link rel="stylesheet" href="css/style.css">
		<!--[if lt IE 10]>
    <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="images/ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <script src="js/html5shiv.min.js"></script>
		<![endif]-->
  </head>
  <body>
    <!-- Page-->
    <div class="page text-center">
      <!-- Page Contents-->
      <section class="page-content bg-gray-dark bg-gray-gradient-after">
        <div class="one-page">
          <div class="shell">
            <div class="one-page-header">
              <!--Navbar Brand-->
              <div class="rd-navbar-brand"><div class="rd-navbar-brand"><img src="images/03.png" class="img-fluid logo" style="width:150px"  alt="img" ></div>
            </div>
          </div>
          <!-- 404-->
          <div class="context-dark">
            <div class="shell">
              <div class="range">
                <div class="section-160 section-md-111 section-cover range range-xs-center range-xs-middle">
                  <div class="cell-lg-12">
                    <div class="text-extra-big text-ubold text-primary">404</div>
                    <h4 class="text-bold offset-top-30 offset-md-top-60">Sorry, But The page is currently under construction</h4>
                    <div class="offset-top-20">
                      <h6 class="text-silver">This page will be up shortly.</h6>
                    </div>
                    <div class="group-xl offset-top-30 offset-md-top-70"><a class="btn btn-primary btn-circle"  style="box-shadow: 0 6px 22px 0 #161616;" href="index.html">back to home page</a><a class="btn btn-white-outline btn-circle"  style="box-shadow: 0 6px 22px 0 #161616;"href="contacts.html">contact us</a></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="one-page-footer">
            <div class="shell">
                <p class="text-white-05">
                    Achieve solutions 
                    &#169;<span id="copyright-year"></span> Design by <a class="text-alto" href="http://www.brainlabs.co.ke/" target="_blank"> brain Labs
                      <!-- {%FOOTER_LINK}--></a>
                  </p>
            </div>
          </div>
        </div>
      </section>
    </div>
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- PhotoSwipe Gallery-->
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="pswp__bg"></div>
      <div class="pswp__scroll-wrap">
        <div class="pswp__container">
          <div class="pswp__item"></div>
          <div class="pswp__item"></div>
          <div class="pswp__item"></div>
        </div>
        <div class="pswp__ui pswp__ui--hidden">
          <div class="pswp__top-bar">
            <div class="pswp__counter"></div>
            <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
            <button class="pswp__button pswp__button--share" title="Share"></button>
            <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
            <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
            <div class="pswp__preloader">
              <div class="pswp__preloader__icn">
                <div class="pswp__preloader__cut">
                  <div class="pswp__preloader__donut"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
            <div class="pswp__share-tooltip"></div>
          </div>
          <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
          <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
          <div class="pswp__caption">
            <div class="pswp__caption__cent"></div>
          </div>
        </div>
      </div>
    </div>
    <!-- Java script-->
    <script src="js/core.min.js"></script>
    <script src="js/script.js"></script>
  </body><!-- Google Tag Manager --><noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-P9FT69"height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-P9FT69');</script><!-- End Google Tag Manager -->
</html>

achievesolapp/templates/achievesolapp/app/events404.html
{% extends 'achievesolapp/base.html' %}
{% load static %}

{% block content %}
    <div class="page text-center" style=" background-color:rgb(34, 34, 34)">
 
      <section class="page-content ">
        <div class="one-page">
          <div class="shell">
            <div class="one-page-header">
         
              <div class="rd-navbar-brand"><img src="{% static "images/3.png" %}"  class="img-fluid logo" style="width:260px"  alt="img" ></div>
            </div>
          </div>
         
          <div class="context-dark">
            <div class="shell">
              <div class="range">
                <div class="section-160 section-md-111 section-cover range range-xs-center range-xs-middle" >
                  <div class="cell-lg-12">
                      <div class="shell-fluid">
                          <!-- <div class="group-xl offset-top-0 offset-md-top-0"></div>
                                  </div> -->
                      
                        <div class="range range-xs-center range-md-left text-left">






                          
                          <div class="cell-xs-10 cell-sm-8 cell-md-4" style="box-shadow: 0 6px 22px 0  #505050;">
                            <article  class="post post-event"><a class="post-image-wrap" href="#">
                                <div class="post-event-date">
                                  <div></div> July 28th 2019
                                </div><img class="img-responsive" src="{% if event.image %} {{ event.image.cdn_url }} {% else %} {% static 'images/blogdefault.jpg' %} {% endif %}"  width="570" height="330" alt=""/></a>
                              <h4 class="text-bold"><a style="color:#fff" href="#"> MaryHill Girls High School Motivational Talk and Mentorship</a></h4>
                              <h4 >Achieve Solutions Talk and Mentorship with a difference</h4>
                              <ul class="list-inline list-inline-md">
                                <li><span class="icon mdi mdi-clock text-middle"></span>
                                  <time style="color:#fff" class="text-middle" datetime="2016-04-30"> 12pm - 4pm   </time> 
                                </li>
                                <li><span class="icon mdi mdi-map-marker text-middle"></span><span style="color:#fff" class="text-middle">MaryHill Girls High School</span></li>

                               

                                <li><span class="icon mdi mdi-ticket text-middle"></span><span class="text-middle"> Free event </span></li>
                              </ul>
                              <!-- <a class="btn btn-circle btn-primary" style="box-shadow: 0 6px 22px 0 #575656;"  href="{% url 'achievesolapp:eventbooking' %}" >book now</a> -->
                            </article>
                          </div>
                             
                          
                        </div>
                      </div>
                    <!-- <div class="text-extra-big text-ubold text-primary"></div>
                    <h2 class="text-bold offset-top-30 offset-md-top-60">No past event found</h2>
                    <div class="offset-top-20">
                      <h6 class="text-silver"></h6>
                    </div> -->
                    <div class="group-xl offset-top-30 offset-md-top-70"><a class="btn btn-primary btn-circle"  style="box-shadow: 0 6px 22px 0 #161616;" href="{% url 'achievesolapp:product_list' %}" >back to events</a><a class="btn btn-white-outline btn-circle"  style="box-shadow: 0 6px 22px 0 #161616;"  href="{% url 'achievesolapp:contact' %}" >contact us</a></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="one-page-footer">
            <div class="shell">
              <p class="text-white-05">
                Achieve solutions 
                &#169;<span id="copyright-year"></span> Design by <a class="text-alto" href="http://www.brainlabs.co.ke/" target="_blank"> brain Labs
               </a>
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- PhotoSwipe Gallery-->
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="pswp__bg"></div>
      <div class="pswp__scroll-wrap">
        <div class="pswp__container">
          <div class="pswp__item"></div>
          <div class="pswp__item"></div>
          <div class="pswp__item"></div>
        </div>
        <div class="pswp__ui pswp__ui--hidden">
          <div class="pswp__top-bar">
            <div class="pswp__counter"></div>
            <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
            <button class="pswp__button pswp__button--share" title="Share"></button>
            <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
            <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
            <div class="pswp__preloader">
              <div class="pswp__preloader__icn">
                <div class="pswp__preloader__cut">
                  <div class="pswp__preloader__donut"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
            <div class="pswp__share-tooltip"></div>
          </div>
          <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
          <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
          <div class="pswp__caption">
            <div class="pswp__caption__cent"></div>
          </div>
        </div>
      </div>
    </div>
    {% endblock%}

achievesolapp/templates/achievesolapp/app/medialist.html
{% extends 'achievesolapp/base.html' %}
{% load static %}

{% block content %}

    <div class="page text-center">
      <!-- Page Head-->
      <header class="page-header slider-menu-position">
              <!-- RD Navbar Transparent-->
              <div class="rd-navbar-wrap">
                <nav class="rd-navbar rd-navbar-top-panel rd-navbar-default rd-navbar-white rd-navbar-static-fullwidth-transparent" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-md-stick-up-offset="90px" data-lg-stick-up-offset="75px" data-auto-height="false" data-lg-auto-height="true" data-layout="rd-navbar-fixed" data-xs-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fullwidth" data-lg-layout="rd-navbar-static" data-sm-stick-up="true" data-md-stick-up="true" data-lg-stick-up="true">
                  <div class="rd-navbar-inner">
                    <!-- RD Navbar Panel-->
                    <div class="rd-navbar-panel">
                      <!-- RD Navbar Toggle-->
                      <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar, .rd-navbar-nav-wrap"><span></span></button>
                      <!-- Navbar Brand-->
                      <div class="rd-navbar-brand"><img src="{% static "images/3.png" %}" class="img-fluid logo" style="width:260px"   alt="img" ></div>
                    </div>
                    <div class="rd-navbar-menu-wrap">
                      <div class="rd-navbar-nav-wrap">
                        <div class="rd-navbar-mobile-scroll">
                          <div class="form-search-wrap">
                            <!-- RD Search Form-->
                            <form class="form-search rd-search" action="search-results.html" method="GET">
                              <div class="form-group">
                                <label class="form-label form-search-label form-label-sm rd-input-label" for="rd-navbar-form-search-widget">Search</label>
                                <input class="form-search-input input-sm form-control form-control-gray-lightest input-sm" id="rd-navbar-form-search-widget" type="text" name="s" autocomplete="off">
                              </div>
                              <button class="form-search-submit" type="submit"><span class="fa fa-search"></span></button>
                            </form>
                          </div>
                          <!-- RD Navbar Nav-->
                          <ul class="rd-navbar-nav">
                            <li><a href="{% url 'achievesolapp:home' %}"><span>Home</span></a>
                           
                            </li>
                            <li><a href="{% url 'achievesolapp:about' %}" ><span>Who we are</span></a>
                            
                            </li>
                            <li><a href="{% url 'achievesolapp:services' %}" ><span>Our Services</span></a>
                              
                            </li>
                            <li><a href="{% url 'achievesolapp:programs' %}" ><span>Our programs</span></a>
                            </li>
                            <li><a href="{% url 'achievesolapp:product_list' %}" ><span>Events</span></a>
                            </li>
                            <li   class="active"  ><a href="{% url 'achievesolapp:media_list' %}" ><span>Gallery</span></a>
                            </li>
                            <li><a href="{% url 'achievesolapp:blog_list' %}"  ><span>Blog</span></a>  
                            </li>
                            <li><a href="{% url 'achievesolapp:contact' %}"  ><span>contact</span></a></li>
                          </ul>
                        </div>
                      </div>
                      <!-- RD Navbar Search-->
                     
                    </div>
                  </div>
                </nav>
              </div>
      <!-- Modern Breadcrumbs-->
      <div class="section-height-800 breadcrumb-modern context-dark text-center breadcrumbs-center">
        <div class="shell section-bottom-120">
          <div class="veil reveal-md-block">
            <h3 class="text-bold">Gallery</h3>
            <ul class="list-inline-custom">
              <li><a class="icon fa fa-facebook  icon-circle icon-gray-light" href="https://www.facebook.com/achievesol/" target="_blank"></a></li>
              <li><a class="icon fa fa-twitter  icon-circle icon-gray-lightt" href="https://twitter.com/achievesol" target="_blank"></a></li>
              <li><a class="icon fa fa-instagram  icon-circle icon-gray-lightg" href="https://www.instagram.com/achievesolutions/" target="_blank"></a></li>
    
            </ul>
          </div>
<!-- 
          <ul class="list-inline list-inline-with-arrows p">
      
            <li><a class="text-white" href="{% url 'achievesolapp:media_list' %}" >PHOTOS</a></li>
            <li><a class="text-white" href="{% url 'achievesolapp:videos' %}" >VIDEOS</a></li>
            
           
          </ul> -->
        </div>
      </div>
    </header>


 <!-- Page Contents-->
 <section class="section-30 section-md-top-30 section-md-bottom-111">
        <div class="shell-fluid">

            <ul class="list-inline "> 
          <li><a class="btn btn-primary btn-circle"  style="box-shadow: 0 6px 22px 0  #575656;" href="{% url 'achievesolapp:media_list' %}">PHOTOS</a></li> 
          <li><a class="btn btn-primary-outline btn-circle"  style="box-shadow: 0 6px 22px 0  #575656;" href="{% url 'achievesolapp:videos' %}" >VIDEOS</a></li>
          
  </ul> <br>
          <div class="isotope-wrap">
            <div class="row">
              <!-- Isotope Filters-->
              <div class="col-lg-12">
                <div class="isotope-filters isotope-filters-horizontal">
                  <ul class="list-inline list-inline-sm">
                      <li class="section-relative">
                          <button class="isotope-filters-toggle btn btn-sm btn-default" data-custom-toggle="isotope-1" data-custom-toggle-disable-on-blur="true">Filter Gallery<span class="caret"></span></button>
                          <ul class="list-sm-inline isotope-filters-list" id="isotope-1">
                              <li {% if not mediacategory %} class="active"{% endif %}><a href="{% url 'achievesolapp:media_list' %}">All</a></li> 
                              {% for category in mediacategories %}
                              <li {% if mediacategory.slug == category.slug %} class="active"{% endif %}>
                                  <a  href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                              </li>
                            {% endfor %}
                          </ul>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
          
              <!-- Isotope Content-->
              <div class="col-lg-12 offset-top-34">
                <div class="isotope" data-isotope-layout="fitRows" data-isotope-group="gallery">
                  <div class="row" data-photo-swipe-gallery="gallery">
                      {% for media in medias %}
                        <div class="col-xs-12 col-sm-6 col-md-4 isotope-item" data-filter="Type 1"><a class="thumbnail-custom" data-photo-swipe-item="" data-size="1200x800" href="{% if media.image %} {{ media.image.cdn_url }} {% else %} {% static 'img/default.png' %} {% endif %}"  style="box-shadow: 0 6px 22px 0 #414141;">
                            <figure ><img style="border-radius: 8px;"  class="img-responsive" width="270" height="100" src="{% if media.image %} {{ media.image.cdn_url }} {% else %} {% static 'img/default.png' %} {% endif %}" alt=""/>
                            </figure></a>
                        </div>
        
                        {% endfor %}
                   
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>



















 <!-- Unordered and Ordered Lists-->

        </div>
        <!-- Global Mailform Output-->
        <div class="snackbars" id="form-output-global"></div>
        <!-- PhotoSwipe Gallery-->
        <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="pswp__bg"></div>
          <div class="pswp__scroll-wrap">
            <div class="pswp__container">
              <div class="pswp__item"></div>
              <div class="pswp__item"></div>
              <div class="pswp__item"></div>
            </div>
            <div class="pswp__ui pswp__ui--hidden">
              <div class="pswp__top-bar">
                <div class="pswp__counter"></div>
                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                <button class="pswp__button pswp__button--share" title="Share"></button>
                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
                <div class="pswp__preloader">
                  <div class="pswp__preloader__icn">
                    <div class="pswp__preloader__cut">
                      <div class="pswp__preloader__donut"></div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div>
              </div>
              <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
              <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
              <div class="pswp__caption">
                <div class="pswp__caption__cent"></div>
              </div>
            </div>
          </div>
        </div>
        {% endblock%}